// Generates a dot-matrix land mask for the Asia-Pacific region used by the
// Global Presence section. Run with `npm run generate:map`.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { feature } from "topojson-client";
import { geoContains } from "d3-geo";

const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8"));
const countries = feature(topo, topo.objects.countries).features;

const LON_MIN = 62;
const LON_MAX = 158;
const LAT_MAX = 40;
const LAT_MIN = -46;
const STEP = 0.8;

// ISO 3166-1 numeric codes for the countries where Armtronix operates.
const TRACKED = { "458": "my", "036": "au", "356": "in" };

const cols = Math.round((LON_MAX - LON_MIN) / STEP) + 1;
const rows = Math.round((LAT_MAX - LAT_MIN) / STEP) + 1;
const out = { land: [], my: [], au: [], in: [] };

// Pre-compute bounding boxes so geoContains only runs on candidate countries.
const boxed = countries.map((f) => {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  const walk = (c) => {
    if (typeof c[0] === "number") {
      minX = Math.min(minX, c[0]); maxX = Math.max(maxX, c[0]);
      minY = Math.min(minY, c[1]); maxY = Math.max(maxY, c[1]);
    } else c.forEach(walk);
  };
  walk(f.geometry?.coordinates ?? []);
  return { f, minX, minY, maxX, maxY };
});

for (let r = 0; r < rows; r++) {
  const lat = LAT_MAX - r * STEP;
  for (let c = 0; c < cols; c++) {
    const lon = LON_MIN + c * STEP;
    const hit = boxed.find(
      (b) => lon >= b.minX && lon <= b.maxX && lat >= b.minY && lat <= b.maxY && geoContains(b.f, [lon, lat]),
    );
    if (!hit) continue;
    const key = TRACKED[String(hit.f.id).padStart(3, "0")];
    (key ? out[key] : out.land).push(c, r);
  }
}

const file = `// AUTO-GENERATED by scripts/generate-map.mjs — do not edit by hand.
// Equirectangular grid: col -> lon = ${LON_MIN} + col * ${STEP}, row -> lat = ${LAT_MAX} - row * ${STEP}
export const MAP_GRID = {
  lonMin: ${LON_MIN},
  latMax: ${LAT_MAX},
  step: ${STEP},
  cols: ${cols},
  rows: ${rows},
} as const;

export const MAP_DOTS: Record<"land" | "my" | "au" | "in", readonly number[]> = {
  land: [${out.land.join(",")}],
  my: [${out.my.join(",")}],
  au: [${out.au.join(",")}],
  in: [${out.in.join(",")}],
};
`;
writeFileSync(new URL("../src/content/map-dots.ts", import.meta.url), file);
console.log(`cols=${cols} rows=${rows} land=${out.land.length / 2} my=${out.my.length / 2} au=${out.au.length / 2} in=${out.in.length / 2}`);
